name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World

  QA:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World

  UAT:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World

  PROD:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World
